version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    image: feed-dev
    container_name: feed-dev
    ports:
      - "8080:8080"         # 호스트의 8080 포트를 컨테이너의 8080 포트와 매핑
    depends_on:
      - redis
    volumes:
      - ~/application_dev.yml:src/main/resources/application.yml
