
server:
    port: 8080

spring:
  datasource:
      url:  ${DATASOURCE_URL_LOCAL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: ${DATASOURCE_DRIVER}

  jpa:
    hibernate:
          ddl-auto: update          # create : 존재하는 table을 전부 drop했다가 다시 생성 -> 테스트용
    properties:
      hibernate:
        format_sql: true
        show_sql: true

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN}

logging:
  level:
    org.hibernate.sql: debug
