spring:
  datasource:
      url:  jdbc:h2:tcp://localhost/~/kuit_space
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
          ddl-auto: update          # table을 전부 drop했다가 다시 생성 -> 테스트용
    properties:
      hibernate:
        format_sql: true
        show_sql: true

secret:
  jwt-secret-key: 8973596554fdf482ddb1fa45a5e1ef9b0a3346232d26279c8cf6aa8b37609e7f
  jwt-expired-in: 3600000

logging:
  level:
    org.hibernate.sql: debug
